sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t glaydsonvs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true glaydsonvs/react-test npm test

after_success:
  - docker build -t glaydsonvs/multi-client ./client
  - docker build -t glaydsonvs/multi-nginx ./nginx
  - docker build -t glaydsonvs/multi-server ./server
  - docker build -t glaydsonvs/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push glaydsonvs/multi-client
  - docker push glaydsonvs/multi-nginx
  - docker push glaydsonvs/multi-server
  - docker push glaydsonvs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-901842438664
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY